apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: custom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: project
        image: iamishan/imagenew
        ports:
        - containerPort: 80
